### ISSUE TITLE
Data Service

### ISSUE THREAD

**Issue by blackbaud-brandonhare** [blackbaud/stache2#131]
We should have a data service in stache that would allow users to access custom data in their stache projects.
1. Have a `data` directory in the `stache` directory
2. Have a plugin that takes each `json` (and possibly yml) file and puts it into the service.
3. The service should surface an API that allows you to pass the file name and get the data from that file.

**Comment by Blackbaud-SteveBrush** [comment]
Determined as too much effort, when the consumer can simply write a http component.
