### ISSUE TITLE
Tutorial Navigation

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/stache2#151]
### Expected behavior
We need to add some kind of navigation to the tutorial layout.

### Actual behavior
It doesn't have a nav.

**Comment by Blackbaud-SteveBrush** [comment]
Closing this issue; added to "Ideas" in [Components Project](https://github.com/blackbaud/stache2/projects/2).

**Comment by Blackbaud-BrandonJones** [comment]
No longer have a Components Project section.

**Comment by Blackbaud-LindseyRix** [comment]
This work is complete and now available in Stache. You can enable the TOC on a tutorial and it helps you navigate as you go.
