### ISSUE TITLE
Ability to search site content

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/stache2#170]

**Comment by Blackbaud-LindseyRix** [comment]
The new omnibar has a search component, would this work for what we need?

**Comment by blackbaud-brandonhare** [comment]
We could enable post build plugin capability in builder and then:
- Create a plugin that would scrape all HTML content.
- Consolidate that content into a JSON object that includes routes from the appConfig
- Create a service that searches that content and a component that displays results on a page.
