### ISSUE TITLE
[rc] Fragments (URL hashes) do not scroll the window to the element

### ISSUE THREAD

**Issue by Blackbaud-LindseyRix** [blackbaud/stache2#178]
An anchor link on the site like:
https://host.nxt.blackbaud.com/engineering-system-docs/learn/create-release-microservice#create-a-project-for-a-new-microservice

goes to:
https://host.nxt.blackbaud.com/engineering-system-docs/learn/create-release-microservice

It doesn't jump down the page to the page anchor. This should be fixed (please!)

**Comment by Blackbaud-SteveBrush** [comment]
Might be related: https://github.com/blackbaud/skyux-builder/blob/80b34027eb0c4e127bd16866bc5088ce6cf14af9/src/app/app.component.ts#L83
