### ISSUE TITLE
Document > Layout Components (API Reference)

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/stache2#203]
{
      name: 'Layout',
      route: '/contribute/components/layout',
      icon: 'map-o',
      summary: 'Component interface between the stache wrapper and layouts.'
    },
    {
      name: 'Layout: Blank',
      route: '/contribute/components/layout-blank',
      icon: 'map-o',
      summary: 'Basic page layouts using Stache and skyux pattern, for quick page layouts.'
    },
    {
      name: 'Layout: Container',
      route: '/contribute/components/layout-container',
      icon: 'map-o',
      summary: 'Basic page layouts using Stache and skyux pattern, for quick page layouts.'
    },
    {
      name: 'Layout: Sidebar',
      route: '/contribute/components/layout-sidebar',
      icon: 'map-o',
      summary: 'Basic page layouts using Stache and skyux pattern, for quick page layouts.'
    },

**Comment by Blackbaud-LindseyRix** [comment]
We resolved this need a new way. Thanks for the feedback.
