### ISSUE TITLE
Variable bindings cannot be used in `pageTitle` and `navTitle` attributes

### ISSUE THREAD

**Issue by blackbaud-brandonhare** [blackbaud/stache2#231]
Because of the route metadata plugin, using variables in `pageTitle` and `routeTitle` attributes doesn't work. There may be a way to fix that by injecting the jsonData service into the routeMetadata service, but that will only work for variables in jsonData.

**Comment by Blackbaud-SteveBrush** [comment]
Related: https://github.com/blackbaud/stache2/issues/255

**Comment by Blackbaud-SteveBrush** [comment]
From Paul C.: "You could add special logic if the `pageTitle` attribute is bound to `stache.jsonData?.etc` and resolve it a build time that way."

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-BrandonJones Would you like to try your hand at this one?
