### ISSUE TITLE
Generate Communication feed

### ISSUE THREAD

**Issue by blackbaud-brandonhare** [blackbaud/stache2#244]
Need a way to generate and maintain a a communication (like RSS) feed for a stache site. This will allow updates to be broadcast to Slack and facilitate communication. Could possibly use existing functionality in VSTS to integrate with Slack.

**Comment by Blackbaud-SteveBrush** [comment]
Closing this issue; added to "Ideas" in [Components Project](https://github.com/blackbaud/stache2/projects/2).

**Comment by Blackbaud-LindseyRix** [comment]
We're looking into implementing this in a different way. Closing this issue for now.
