### ISSUE TITLE
JSON data cannot be used in `<stache>` or `<stache-code-block>` bindings

### ISSUE THREAD

**Issue by Blackbaud-BrandonJones** [blackbaud/stache2#255]
### Expected behavior
I should be able to use global json data anywhere in my app.
### Actual behavior
When adding global json data to attributes such as `pageTitle` angular throws an `ExpressionChangedAfterItHasBeenCheckedError`.   Investigate a way to force a digest cycle after that value has been changed in order to prevent it from happening in dev environments.  
https://hackernoon.com/everything-you-need-to-know-about-the-expressionchangedafterithasbeencheckederror-error-e3fd9ce7dbb4

When using global json data in codeblock, it does not replace the text content... this is by design normally, but it would be nice to find a way to escape content we want to render.  

### Steps to reproduce
try to use the global json data in the `<stache pageTitle=' {{ stache.jsonData.global.productName }}'> `  or `<stache-code-block> {{ stache.jsonData.global.productVersion }} </stache-code-block>`

**Comment by Blackbaud-SteveBrush** [comment]
Related: https://github.com/blackbaud/stache2/issues/231
