### ISSUE TITLE
`stache-page-anchor` does not accommodate Omnibar

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [blackbaud/stache2#304]
### Expected behavior

If the "new" omnibar is on a page, clicking or loading a link to a `stache-page-anchor` should clearly load the contents of the `stache-page-anchor`.

### Actual behavior

The contents of the `stache-page-anchor` are "under" the omnibar.

### Steps to reproduce

Visit https://docs.blackbaud.com/engineering-system-docs/standards/web-service-dev#create-web-services and notice the title is not fully visible.

As a suggestion, I think the easiest fix for this is to increase the `margin-top` of `.stache-page-anchor` by `2em`, then offset that by making the `padding-top` `-2em`.  It would be even more awesome to conditionally set this whether the Omnibar was present, but it's my opinion that having a title with a little extra space is better than a title not fully visible.

**Comment by Blackbaud-BobbyEarl** [comment]
Dang.  Cold @Blackbaud-LindseyRix.  Can I get a "fixed in X?"  :-)

**Comment by blackbaud-brandonhare** [comment]
Fixed in #317
