### ISSUE TITLE
SKY UX inline text styles unavailable due to more specific stache selectors

### ISSUE THREAD

**Issue by Blackbaud-MattGregg** [blackbaud/stache2#308]
Inline text styles – I wanted to use the de-emphasized class from SKY UX2 (https://developer.blackbaud.com/skyux2/design/typography) and found that the stache CSS declarations for .stache-wrapper p override some CSS properties from SKY UX2.
Would be very nice to be able to use the SKY UX 2 classes and get same display output.

**Comment by Blackbaud-BrandonJones** [comment]
Resolved in #579
