### ISSUE TITLE
Sidebar nav displays horizontal scrollbar after it locks into position

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/stache2#316]
### Expected behavior
The sidebar nav does not display a horizontal scrollbar before or after the nav locks into position..

### Actual behavior
On sidebar navs with long headers (like the word "documentation"), a horizontal scrollbar appears when users scroll down on pages to the point where the sidebar navs lock into place. In Firefox, where this behavior was initially pointed out, the scrollbar appears if the browser is maximized. If not, the scrollbar doesn't appear, but the header overlaps the page text. In Chrome, the scrollbar appears regardless of whether the browser is maximized.

### Steps to reproduce
Got to https://developer.blackbaud.com/skyux2/design, select a child topic, and scroll down.

**Comment by Blackbaud-LindseyRix** [comment]
Resolved.
