### ISSUE TITLE
Height and Width as properties for <stache-image>

### ISSUE THREAD

**Issue by Blackbaud-LindseyRix** [blackbaud/stache2#318]
Currently, the only property I can set on a `<stache-image>` is the source and alt tag. It would be nice if we could provide an image width and/or height to size the image on the page. 

This would give us the ability to better fit the image on the page without having to edit every source file. 

Ideally, it would be nice to prevent people from skewing the image, but not sure if there is a way to force the image to stay in proportion.

**Comment by Blackbaud-BrandonJones** [comment]
To accomplish this you would simply put a "wrapping" element around your `<stache-image>`.

ie:
```
<div class="half-size">
  <stache-image
    alt="foo image"
    source="~/assets/foo.jpg">
  </stache-image>
</div>
```

then add your styles for heigh and width to the css for `.half-size`.

**Comment by Blackbaud-LindseyRix** [comment]
I'd prefer not to have to edit the CSS, or ask someone else to, every time they want to add an image to a page.
