### ISSUE TITLE
Docs: Support Sharepoint videos with video component

### ISSUE THREAD

**Issue by Blackbaud-MattGregg** [blackbaud/stache2#319]
Request:
Would be nice to be able to use videos in a sharepoint site such as this - https://blackbaud.sharepoint.com/sites/accessibility/_layouts/15/guestaccess.aspx?guestaccesstoken=rTmAw6DCTEPIZuPHckL48v0oCKRfYsfxFikTXk%2fV7fQ%3d&docid=2_15438c20032b44c069de274f017303e11&rev=1

I have videos that don't seem to really be the right kind of content or have a channel on the [Videos area of O365](https://blackbaud.sharepoint.com/portals/hub/_layouts/15/PointPublishing.aspx?app=video&p=h) unless there is some way to have a folder of videos to host.

Related, it took me some time to figure out what the O365 Video thing even was. I tried using this Sharepoint method at first before realizing it didn't work and going through help docs I discovered there was this Videos thing in O365. A link to it in the [video component docs](https://developer.blackbaud.com/stache/content/video) would be useful I think.

**Comment by Blackbaud-LindseyRix** [comment]
We're going to add a link to the O365 Stache video channel in our docs, but wanted to provide you a link to the new channel:
https://blackbaud.sharepoint.com/portals/hub/_layouts/15/PointPublishing.aspx?app=video&p=c&chid=9006bebc-4c88-4c22-b5f0-159f455957fe&s=0&t=pfb
