### ISSUE TITLE
Serving on IE

### ISSUE THREAD

**Issue by Blackbaud-BrandonJones** [blackbaud/stache2#322]
### Expected behavior
I should be able to Serve the Stache 2 project locally, I should be able to serve and view it in IE 11.

### Actual behavior
Serving the project in IE causes the browser to refresh and crash.

### Steps to reproduce
clone the project locally on a windows machine, `skyux serve` and launch in IE.

**Comment by Blackbaud-LindseyRix** [comment]
Refer to SKYUX docs for how to serve locally on IE.
