### ISSUE TITLE
Smooth Scroll in FF and Chrome 61

### ISSUE THREAD

**Issue by Blackbaud-BrandonJones** [blackbaud/stache2#330]
### Expected behavior
Clicking on an anchor link should scroll the browser to the element

### Actual behavior
In Chrome 61 and Firefox it Jumps directly to the element when the `this.windowRef.nativeWindow.location.hash` is changed. Without adding the hash this way, the behavior has changed to scroll the element to the center of the page instead of the top.  adding `block: 'start'` fixes this behavior, though the `location.hash` still needs to be updated to not snap to the element.

### Steps to reproduce

Visit any Stache 2 site with page anchors (easiest if table of contents also exists.)
https://host.nxt.blackbaud.com/stache/learn/plugins

**Comment by blackbaud-brandonhare** [comment]
Resolved #378
