### ISSUE TITLE
Search button and text input have different border colors

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/stache2#332]
<img width="162" alt="screen shot 2017-10-02 at 2 42 33 pm" src="https://user-images.githubusercontent.com/12497062/31194698-fd93cc4a-a915-11e7-85fd-e4f0fab74642.png">

**Comment by Blackbaud-BrandonJones** [comment]
https://github.com/blackbaud/skyux2/issues/1182
Sky issue, will not address.
