### ISSUE TITLE
Page Anchor icon does not appear in IE11

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/stache2#333]
<img width="613" alt="screen_shot_2017-10-06_at_10 49 10_am" src="https://user-images.githubusercontent.com/12497062/31283690-506de7ec-aa84-11e7-8967-319f6ee26d0f.png">

**Comment by Blackbaud-BrandonJones** [comment]
Fixed in this PR: https://github.com/blackbaud/stache2/pull/462
