### ISSUE TITLE
Feature Request: Add Highlight to Markdown

### ISSUE THREAD

**Issue by blackbaud-NikkiTremann** [blackbaud/stache2#352]
Would be great to have a highlighter component in Stache 2 markdown.

Use Case: I'm building a site for Prof Services. I need to highlight the areas that need review and additional content they need to provide.

**Comment by blackbaud-brandonhare** [comment]
If you just want to highlight some text, you can use the `<mark></mark` tags. They'll highlight anything between them in yellow.
