### ISSUE TITLE
Remove SKY UX as a dependency

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/stache2#355]
Because Stache is bundled as a JavaScript library, when UX docs reference the module, it is inadvertently referencing two versions of SKY UX: 1) The version that is currently in the master branch of SKY UX, and 2) the version that Stache requires.

Solution: remove (or come up with something unique) any reference to the Sky Action Button and Sky Search components.

If we can avoid a breaking change, that would be ideal.

**Comment by Blackbaud-LindseyRix** [comment]
Resolved by SKY UX.
