### ISSUE TITLE
Investigate direct link to git file.

### ISSUE THREAD

**Issue by Blackbaud-BrandonJones** [blackbaud/stache2#360]
Investigate adding a direct link mechanism to link to the `git file` for specific pages.  Requested by @Blackbaud-TimothyWittig "It makes it a little harder to contribute or view the history of a file with out that link".  This may be a one off for Engineering System.

**Comment by Blackbaud-LindseyRix** [comment]
This is the old feature we had in Stache 1 that enables you to click the edit button from a page. Would apply to internal sites and public sites enabling community contribution model only.

**Comment by Blackbaud-TommyVernieri** [comment]
The tutorial in blackbaud/stache2-docs#90 can help with this.

**Comment by Blackbaud-LindseyRix** [comment]
Edit button feature released. https://github.com/blackbaud/stache2/pull/379
