### ISSUE TITLE
Docs: C# Generics Creating self closing tags in code snippets

### ISSUE THREAD

**Issue by blackbaud-brandonhare** [blackbaud/stache2#362]
Timothy Wittig [10:27 AM] 
I'm seeing weirdness in stache 2 code snippets

[10:27] 
e.g. https://host.nxt.blackbaud.com/engineering-system-docs/learn/release-microservice/appservice/logging

[10:28] 
Looks like it's seeing `<SomeCSharpGeneric>` and assuming it's an xml tag and automatically appending close tags (edited)

Steve Brush [10:30 AM] 
Might need to set `recognizeSelfClosing` in the cheerio config https://github.com/fb55/htmlparser2/wiki/Parser-options#option-recognizeselfclosing

[10:31] 
@brandon.jones @brandon.hare

**Comment by blackbaud-brandonhare** [comment]
After discussing and investigating this further with @Blackbaud-BobbyEarl, we've determined that this would take a substantial rewrite of large portions of the stache plugin to accommodate the changes required to fix this issue. cheerio and JSDOC have the same behavior, so this is not isolated to just cheerio. Due to the amount of work involved, the complexity of the changes, and the fragility of the solution, we are shelving this for now and recommending that affected users escape their generics in code samples with HTML Escape characters (&lt; and &gt;).

**Comment by Blackbaud-LindseyRix** [comment]
Add a line to the code block snippet about using the escape character for the less than symbol.

**Comment by Blackbaud-LindseyRix** [comment]
We aren't able to resolve with functionality yet, documented the workaround.
https://developer.blackbaud.com/stache/content/code-block
