### ISSUE TITLE
Search should match partial words

### ISSUE THREAD

**Issue by Blackbaud-BrandonJones** [blackbaud/stache2#367]
### Expected behavior
When typing in the Search bar, after 3-4 letters are entered Search should match "partial" matches.  IE:  typing markd  should show results for `Markdown`. etc.
### Actual behavior
typing `markd` shows 0 search results.

**Comment by blackbaud-brandonhare** [comment]
I actually talked to Paul about this one, and it might not be ideal to add the capability (there's a reason it's not on by default). It could lead to a bunch of garbage hits. I think if we set up aliases that will help some. I also think there's a "fuzzy" search option (where it'll find different versions of the same word, like run, running, etc).
