### ISSUE TITLE
showTableOfContents doesn't pick up stache-page-anchors from within an includes file

### ISSUE THREAD

**Issue by Blackbaud-LindseyRix** [blackbaud/stache2#373]
### Expected behavior

I would expect if i have a `<stache-page-anchor>` within an includes file loaded on a page, that these items would show up in the Table of Contents.

### Actual behavior

The table of contents gets loaded before the includes so they don't appear at all.

### Steps to reproduce

1. Create an includes file with stache page anchors.
2. Add an includes file to a page.
3. Enable the `showTableOfContents` feature.
4. See that your items don't show up.

**Comment by blackbaud-brandonhare** [comment]
Unable to reproduce. I think it's fixed. :)

**Comment by Blackbaud-LindseyRix** [comment]
Thanks for fixing whatever it is that you fixed that makes it work now.
