### ISSUE TITLE
Urls incorrectly parsed in code blocks inside of markdown tags

### ISSUE THREAD

**Issue by blackbaud-brandonhare** [blackbaud/stache2#391]
### Expected behavior
The url should render as a string.

### Actual behavior
The url is wrapped in anchor tags. This is the result of default behavior of the markdown parser. We could potentially override this behavior.

### Steps to reproduce
Put a URL sting inside of a code block and wrap the code block in markdown tags.

**Comment by Blackbaud-LindseyRix** [comment]
Documentation in progress to advise that you close the `stache-markdown` component before you use a Stache or SKY UX component. Then re-open if necessary.
