### ISSUE TITLE
Parse fragments in `stacheRouterLink`

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/stache2#396]
Currently, the `StacheRouterLinkDirective` allows for two separate inputs, `stacheRouterLink` (which accepts the route) and `fragment` (which accepts the route fragment). Since the directive is not truly extending Angular's `RouterLink`, we could potentially parse both inputs from `stacheRouterLink`. For example: `<a stacheRouterLink="foo/bar" fragment="baz">` would become `<a stacheRouterLink="foo/bar#baz">`.

**Comment by Blackbaud-LindseyRix** [comment]
We appreciate your feedback. At this time, we have chosen to stick with Angular best practices and not change how we support fragments.
