### ISSUE TITLE
Stache2 in folder path causes errors

### ISSUE THREAD

**Issue by Blackbaud-BrandonJones** [blackbaud/stache2#402]
If the folder structure of a user containst `/stache2/` or `\stache2\` our plugin tries to redirect their resources to call from `'./public'` which results in an error and being unable to serve.  We did this so our Stache 2 library could be detected and change our resource path for us.  However we should be more specific about where in the resource path the `stache2` is searched for.

**Comment by Blackbaud-LindseyRix** [comment]
This has been documented. @Blackbaud-BrandonJones Do you still want to make the engineering change or is a docs change good enough for now?

**Comment by Blackbaud-BrandonJones** [comment]
The docs change would be a place holder, an engineering task should still be done for this.  I think it would be a great starter project for the engineer who joins our team. It would get them familiar with the plugin relationship with Stache, builder, and the stache plugin.
