### ISSUE TITLE
Docs - Make step 1 in Pre-reqs more recognizable 

### ISSUE THREAD

**Issue by Blackbaud-BrandonJones** [blackbaud/stache2#403]
https://docs.blackbaud.com/stache/learn/get-started#install-sky-ux-prerequisites

The first step (the SSL stuff) seems to blend into step 2, because of the alerts separating the other steps, missing step 1 was easier to do than we want.  We should find a way to make sure that is easier to distinguish for scan readers.

**Comment by Blackbaud-LindseyRix** [comment]
Resolved with re-write of pre-reqs
