### ISSUE TITLE
Clearer redirect from Provisioning Portal

### ISSUE THREAD

**Issue by Blackbaud-BrandonJones** [blackbaud/stache2#404]
https://docs.blackbaud.com/stache/learn/get-started/new-stache#create-and-provision-your-sky-ux-application-in-the-app-management-portal

Using the App management portal sends them to Engineering System to set up their SPA in VSTS (I believe) once that repo is created, they are prompted with steps to use `skyux new` to create your new SKYUX 2 SPA, and we lose track of where we are in the tutorial.  We should either add an alert of sorts to continue with our docs after they provision their repo, OR update the engineering system so that once the repo is created, we link back to Stache2 docs if they want a stache site.  It might be worth even creating a new app management portal in the engineering system for a docs site, where we can enforce our own naming strategy.

**Comment by Blackbaud-LindseyRix** [comment]
Do you think we could ask SKY UX to provide an alert/instructions in their app management portal page to send users back to our instructions if they are creating a Stache site?

**Comment by Blackbaud-BrandonJones** [comment]
I am creating a PR for this now :)

**Comment by Blackbaud-LindseyRix** [comment]
🏅

**Comment by Blackbaud-BrandonJones** [comment]
https://blackbaud.visualstudio.com/Products/_git/skyux-spa-skyux-apps/pullrequest/10585?_a=files

**Comment by Blackbaud-LindseyRix** [comment]
App Management Portal has been updated.
