### ISSUE TITLE
Docs: How to update app nav to experimental omnibar

### ISSUE THREAD

**Issue by Blackbaud-LindseyRix** [blackbaud/stache2#411]
Since our template can't contain the new omnibar, we should find a place to document for a Stache user (ex. tech writer on User Ed) how to get rid of the old app-nav and go to new omnibar with search enabled. May want to include the edit feature too. 

Would need to document in a bb user only location and link to it from Stache docs.

**Comment by Blackbaud-BrandonJones** [comment]
Perhaps we should consider having a section on the `skyuxconfig.json` file, the properties we want people to add for internal use (search, name, plugins etc.)  and have the omnibar stuff under there?

**Comment by Blackbaud-LindseyRix** [comment]
Resolved with new internal template.
