### ISSUE TITLE
Codeblock stripping </param> tag

### ISSUE THREAD

**Issue by Blackbaud-BrandonJones** [blackbaud/stache2#417]
### Expected behavior
Using a code block in either markdown or html should render both the opening and closing `<param></param>` tags.
### Actual behavior
the opening `<param>` tag renders, the closing is stripped out.
### Steps to reproduce
<stache-code-block languageType="cshap">
  <param name="foo">Bar</param>
</stache-code-block>

**Comment by Blackbaud-LindseyRix** [comment]
At this time, we will not address. We can reopen if there's a potential solution.
