### ISSUE TITLE
Null Results in Search

### ISSUE THREAD

**Issue by Blackbaud-LindseyRix** [blackbaud/stache2#418]
Paul Gibson noticed null results when searching for `Cosmos Db` –
https://files.slack.com/files-pri/T02BBN218-F9M7HEH27/image.png

We should:
1) Find out if it's content not rendering.
or, if that page doesn't have content
2) Filter out the null results until there is content.

**Comment by Blackbaud-BrandonJones** [comment]
https://blackbaud.visualstudio.com/Products/User%20Ed%20-%20SDK%20API/_git/skyux-spa-docs-search/pullrequest/12054?_a=overview

**Comment by Blackbaud-BrandonJones** [comment]
The null results still show because the search term matches either the title or the url in some segment. Unsure of the desired behavior here, but until then, that PR will at least not display "null" in the description field for IE and Edge if the returned result does not contain a description
