### ISSUE TITLE
Investigate bug when sidebar nav includes lots of items.

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/stache2#420]
### Expected behavior
Sidebar nav with lots of items allows the user to scroll down and access all items in the list.

### Actual behavior
If the sidebar nav has a lot of items and you scroll down, the SPA spazzes out. In the bulk import reference docs, we have 2 reference sections with lots of topics for reference tables. In one, the tables are deeply nested, and when you access the most deeply nested section and scroll down, the screen everything on the page flashes as if the screen were shaking and the page becomes nonresponsive (although you can use the Esc to get out of this). You cannot access these topics from the sidebar nav. The initial assumption was that the problem was too many levels of nesting, but I found the same behavior in the other reference section. That section only nested 1 level down, but it had a lot of child topics with tables, which resulted in a very long list of links in the sidebar nav. When that sidebar is in place, the page spazzes out when you scroll down just like the other reference section with the nesting. I reorganized the topic to group tables and nest one more level down to avoid the long list, but I still run into issues in the section with the most tables because that list is still fairly long. We either need to fix this behavior or provide guidance to explicitly limit the number of items in the sidebar nav.

### Steps to reproduce
Create a topic with a lot of child topics and use the sidebar nav.

### Plunker (see example SKY UX 2 plunker template at: https://plnkr.co/edit/GeP22YbirEzceF3NVu39?p=preview)
No Plunker, but I can demonstrate this behavior in the bulk import reference docs.

**Comment by blackbaud-johnly** [comment]
I played around with this some more, and I think it is connected to displaying the scroll bar in the sidebar nav when the browser is maximized. 

When the browser is maximized, the behavior seems to be connected to displaying the scroll bar in the sidebar nav on pages where the content of the page is shorter than the sidebar nav. The page shaking occurs when all of the page's content is visible and you scroll down primarily to access nav items. When you hit the point where the the scrollbar should pop up, the scroll bar appears just before the entire page starts shaking. You can hit the back button to refresh the site, but you can't scroll down further. However, on longer topics where the content goes past the bottom of the screen, the scroll bar appears in the sidebar nav as you scroll down through the content on the page.

When I minimized the size of the browser to see the behavior on medium-length topics, scrolling did not cause the page shaking that I see when the browser is maximized.

**Comment by Blackbaud-BrandonJones** [comment]
https://github.com/blackbaud/stache2/pull/438 resolved
