### ISSUE TITLE
TOC not loading on production site

### ISSUE THREAD

**Issue by Blackbaud-LindseyRix** [blackbaud/stache2#422]
Browser: Chrome, V 64.0.3282.186.

Noticed by two people for this page:
https://docs.blackbaud.com/devops-docs/shared-services/maintenance/Update-Application/Update-Manual

Does not happen every single time. May be related to similar issue that happens in "local mode."

Reported by: Sean Southard

**Comment by Blackbaud-BrandonJones** [comment]
https://github.com/blackbaud/stache2/pull/441 Resolved
