### ISSUE TITLE
Switching between pages causes shifting of sidebar nav + breadcrumbs

### ISSUE THREAD

**Issue by Blackbaud-LindseyRix** [blackbaud/stache2#424]
On the learn > getting started > tutorials....note that if you toggle between tutorial 1 and tutorial 2, the page margins jump around so that the page contents section shifts to the left a bit.  

https://docs.blackbaud.com/uiextensibility-docs/learn/tutorials/tutorial-two

Lindsey has an animated gif of it happening. GH is not letting me upload files from work so will attach to backlog item.

Reported by: Ben Lambert
- Chrome latest version - looks to be 64.0.3282.186

**Comment by Blackbaud-LindseyRix** [comment]
Per @Blackbaud-BrandonJones, it’s only on windows machines in chrome, it is the scroll bar showing up.

**Comment by Blackbaud-LindseyRix** [comment]
When observing this happen on Ben's computer, it appears that this happens when the page goes from being within the view to requiring a user to scroll down the page. When that happens, the page scrollbar appears on the right (previously hidden), and causes the content to shift on the page. 
- Happens on Windows, Chrome
- Doesn't happen on Mac, Chrome

**Comment by Blackbaud-BrandonJones** [comment]
This was addressed in release 2.8.0 https://github.com/blackbaud/stache2/pull/486
Ben Lambert has been contacted and notified.
