### ISSUE TITLE
Remove query string params from breadcrumbs

### ISSUE THREAD

**Issue by Blackbaud-BrandonJones** [blackbaud/stache2#425]
### Expected behavior
Breadcrumbs should not display the route params
### Actual behavior
Navigating within a Stache page with route params, adds the params to the bread crumbs.
### Steps to reproduce
https://docs.blackbaud.com/engineering-system-docs/standards?foo=bar

breadcrumbs show the params

**Comment by Blackbaud-LindseyRix** [comment]
Reported in Engineering System Slack channel that this issue is affecting page anchors and the ability to select them.

**Comment by Blackbaud-BrandonJones** [comment]
https://github.com/blackbaud/stache2/pull/426
