### ISSUE TITLE
URL queries break page anchor heading links

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/stache2#427]
For example, go here: https://host.nxt.blackbaud.com/engineering-system-docs/learn?svcid=engsys

Then, click on one of the page anchors' "chain link" icons. You should see a 404 page.

<img width="203" alt="screen shot 2018-03-22 at 8 56 11 am" src="https://user-images.githubusercontent.com/12497062/37771751-ee5d45a8-2dae-11e8-92c4-37a99d69086d.png">

**Comment by Blackbaud-SteveBrush** [comment]
Might be related: https://github.com/blackbaud/stache2/issues/425

**Comment by Blackbaud-LindseyRix** [comment]
Yes, it's related to #425 . Closing this bug.
