### ISSUE TITLE
Double sidebar scrollbars

### ISSUE THREAD

**Issue by Blackbaud-BrandonJones** [blackbaud/stache2#446]
### Expected behavior
When the side-bar affixes to the top it should only have one scrollbar when it's longer than the page. 
### Actual behavior
Two scrollbars can be seen.
### Steps to reproduce
serve Stache2 and look at the sidebar on the home page when scrolling down.
![screen shot 2018-04-18 at 9 28 31 am](https://user-images.githubusercontent.com/20796436/38934931-06b41a22-42eb-11e8-873f-13235ca2bb83.png)

**Comment by Blackbaud-LindseyRix** [comment]
Fixed.
