### ISSUE TITLE
stacheRouterLink with fragment does not work

### ISSUE THREAD

**Issue by Blackbaud-ChristiSchneider** [blackbaud/stache2#449]
### Expected behavior

Link takes you to intended page.

### Actual behavior

Link does not take you to intended page.

### Steps to reproduce

* Go to [the link demo](https://developer.blackbaud.com/stache/content/link#demo)
* Click "Internal link to Action buttons code sample"
* Note that it takes you to https://developer.blackbaud.com/stache/content/link#demo
* Expected to be directed to https://developer.blackbaud.com/stache/content/action-buttons#code

### Plunker (see example SKY UX 2 plunker template at: 

```
<a stacheRouterLink="/content/action-buttons" fragment="code">Internal navigation link to Action buttons code sample</a>
```

**Comment by Blackbaud-BrandonJones** [comment]
This issue was resolved: thanks for the report!

https://github.com/blackbaud/stache2/pull/452
