### ISSUE TITLE
Components containing stache-page-summary or sky-alert truncate page content

### ISSUE THREAD

**Issue by Blackbaud-ChristiSchneider** [blackbaud/stache2#450]
### Expected behavior

I can include components in a page and the component will appear in place along with the rest of the content.

### Actual behavior

Components containing `stache-page-summary` or `sky-alert` cause the following page content to disappear.

### Steps to reproduce

my-alert.component.html
```
<sky-alert alertType="warning">
  Example text
</sky-alert>
```

index.html
```
<stache pageTitle="Example Page" showTableOfContents="true">
  
  <stache-page-summary>
    This is the summary
  </stache-page-summary>

  <p>This content will appear</p>

  <my-alert />

  <p>This content will not appear</p>

</stache>
```

Same behavior occurs when using a component containing `stache-page-summary`.

### Plunker 

Unfortunately this appears to be related to builder so I was unable to get a plunker that demonstrates the issue.

**Comment by Blackbaud-BrandonJones** [comment]
I think this behavior can be avoided if you don't use a self closing tag for your component.
`<my-alert></my-alert>` will allow the rest of the content to be displayed.

**Comment by Blackbaud-BrandonJones** [comment]
I think this is an angular issue. 
https://github.com/angular/angular/issues/673

**Comment by Blackbaud-ChristiSchneider** [comment]
Wow thanks, I had no idea.
