### ISSUE TITLE
Stache Code Blocks in Markdown tags

### ISSUE THREAD

**Issue by Blackbaud-BrandonJones** [blackbaud/stache2#453]
### Expected behavior
Using a `<stache-code-block>` within the `<stache-markdown>` component should behave like normal.
### Actual behavior
If the codeblock contains `{` characters, it throws and EOF angular error 
```
Unhandled Promise rejection: Template parse errors:
Unexpected character "EOF" (Do you have an unescaped "{" in your template? Use "{{ '{' }}") to escape it.) ("
  </p>
```
### Steps to reproduce
```
  <stache-markdown>
## This is markdown
<stache-code-block
  languageType="js">
using System;
using Blackbaud.CRM.Core.Domain.Contracts;

namespace Blackbaud.CRM.Widget.Domain.Contracts
{
  "Hello": "World"
}
</stache-code-block>

## This ends markdown
</stache-markdown>
```
In a file.

**Comment by Blackbaud-ShaydeNofziger** [comment]
Not sure what the results of your grooming were, but I believe the issues I'm experiencing are related to this bug - lmk if I should open a separate issue.

Ignoring syntax / the fact that it's mixed languages, observe the effects of starting a code-block line with and without a `#`, at various indentation levels.

```
<stache-markdown>
# Hello, world!

  <stache-code-block>
Function Get-BBGuestComputer {
  return $env:ComputerName
}
$computer = Get-BBGuestComputer
[Google](https://google.com)
  </stache-code-block>
</stache-markdown>
```
Observe that this renders as expected.

```
<stache-markdown>
# Hello, world!

  <stache-code-block>
Function Get-BBGuestComputer {
  return $env:ComputerName
}
# $computer = Get-BBGuestComputer
[Google](https://google.com)
  </stache-code-block>
</stache-markdown>
```
Observe that everything following the `#` renders as markdown. Now try placing `{ }` on the Google line or a new line beneath it, still in the `<stache-code-block>`. Observe the angular error originally mentioned in the OP.

```
<stache-markdown>
# Hello, world!

  <stache-code-block>
    Function Get-BBGuestComputer {
      return $env:ComputerName
    }
    # $computer = Get-BBGuestComputer
    [Google](https://google.com)
  </stache-code-block>
</stache-markdown>
```
Observe that this renders correctly, but note the break into separate code blocks.

**Comment by Blackbaud-LindseyRix** [comment]
At this time, we're not going to address. Instead, we're recommending you close the `stache-markdown` component before the `stache-code-block` and then reopen afterwards.
