### ISSUE TITLE
Investigate standards for sidebar components to better display page layout to the user

### ISSUE THREAD

**Issue by Blackbaud-TimPepper** [blackbaud/stache2#461]
It is possible for the Stache sidebar to be set up in a way such that it is distinguished from the rest of the application. This would allow for a more clear workflow for the user, and would allow for a better standard moving forward as we continue tweaking the Stache layout to provide a better user experience.

[Angular Example](https://angular.io/guide/quickstart)
[Stache Example](https://docs.blackbaud.com/stache/learn/plugins)

We could also consider looking in to ways to better use the screen real estate we have, in general. Stache SPAs tend to leave a lot of white space to the left and right that we can expand in to. The Angular link above is a good example of how we could more effectively use that whitespace.

Most notably, the Angular sidebar sits on the far left of the window, and can be expanded and collapsed to provide more space. The sidebar also automatically collapses when the window gets too thin.

**Comment by Blackbaud-TimPepper** [comment]
[Google Example](https://developers.google.com/web/tools/chrome-devtools/)

**Comment by Blackbaud-LindseyRix** [comment]
The current page-level sidebar has been functioning perfectly, I hope we don't change that part!

**Comment by Blackbaud-BrandonJones** [comment]
I don't think this is a proposal for changing how the sidebar functions, just the style to make it more distinct as a separate item from the rest of the page content.

**Comment by Blackbaud-BrandonJones** [comment]
Addressed in the 2.8.0 release. https://github.com/blackbaud/stache2/pull/486
