### ISSUE TITLE
Skyux tutorial 

### ISSUE THREAD

**Issue by wmaszk** [blackbaud/stache2#468]
### open this url https://host.nxt.blackbaud.com/learn-skyux/tutorials/project-setup/enable-auth-omnibar 
in chrome and pull the browser to the side to fill up half of the screen. Then when you scroll down the text on the page with be obscured by the navigation on the left side

**Comment by Blackbaud-BrandonJones** [comment]
Steps to reproduce:
On a windows machine, drag the browser to the edge of the screen until it "snaps" to half width.  Then scroll down the page and the side bar will be affixed while being over the top of the content.

**Comment by Blackbaud-BrandonJones** [comment]
Should be resolved with https://github.com/blackbaud/stache2/pull/489
