### ISSUE TITLE
Add more Prismjs supported langauges

### ISSUE THREAD

**Issue by Blackbaud-BrandonJones** [blackbaud/stache2#470]
### Expected behavior
We should be able to add some of the newer supported language options to codeblocks from prism

### Actual behavior
Updating to the newest version of prism to support things like `vbnet` syntax causes an error ` Cannot read property 'buildPlaceholders' of undefined`, something introduced with the newest version of prism.

### Steps to reproduce
Update to the latest version of prism in your package.json and install.  try to serve the project.

**Comment by Blackbaud-LindseyRix** [comment]
Notify Derek Britt when vbnet is available to use for syntax highlighting in stache-code-block

**Comment by Blackbaud-LindseyRix** [comment]
We now support most of all the prism languages including vbnet.
