### ISSUE TITLE
Document the 'got-yas' of codeblock within markdown

### ISSUE THREAD

**Issue by Blackbaud-BrandonJones** [blackbaud/stache2#472]
Using a `stache-code-block` within a `stache-markdown` tag creates issues.  First it does not respect blank lines within the codeblock, and often breaks it into separate blocks, which cause errors. Two options exist currently:
A) use the markdown codeblock syntax, 
```
<tictictic>csharp
  ~ code~
<tictictic>
```
replacing each `tic` with a backtic `

B) Close the `stache-markdown` tag, use the `stache-code-block` then open a new `stache-markdown` block.

**Comment by Blackbaud-LindseyRix** [comment]
Include the part about spaces in code blocks, better to close markdown and reopen after.

**Comment by Blackbaud-LindseyRix** [comment]
This has been documented. We now recommend you don't use `stache-code-block` within `stache-markdown`. Instead, we recommend you close and then re-open `stache-markdown` after the code block.
