### ISSUE TITLE
Stache may be overwriting SKY UX header styles

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/stache2#477]
### Expected behavior
Headers in Stache docs with the `sky-subsection-heading` class should be styled the same regardless of whether they are wrapped in a `header` tag.
 
### Actual behavior
While reviewing some UX guidelines, I noticed that some sub-headers in the UX Guidelines section of component docs look different than others. They all use the `sky-subsection-heading` class (inside of a div), but some are wrapped in `header` tags. Todd said the class should style the headers the same regardless of whether we use `header` tags and suggested that Stache is overwriting styles. 

### Steps to reproduce
Create 2 headers using the `sky-subsection-heading` class in `div` tags. Wrap one in a `header` tag but not the other.

### Plunker
No Plunker, but for reference, the action button component has the `header` tag in the subheader under UX Guidelines: https://developer.blackbaud.com/skyux/components/action-button#ux-guidelines. And the button component does not: https://developer.blackbaud.com/skyux/components/button#ux-guidelines.

**Comment by Blackbaud-TimPepper** [comment]
Neither John or myself are able to reproduce this behavior. Closing.

**Comment by Blackbaud-BrandonJones** [comment]
https://github.com/blackbaud/stache2/blob/master/src/app/public/src/modules/wrapper/wrapper.component.scss#L17

Simply removing these styles might cause some issues with our components, we need to figure out which ones to style and not.  Allowing Sky classes to override our styles.
