### ISSUE TITLE
Action buttons shouldn't be buttons

### ISSUE THREAD

**Issue by Blackbaud-BrandonJones** [blackbaud/stache2#481]
### Expected behavior
Buttons should trigger an action on the page, not be used for navigation according to the rules of semantic markup for Accessibility. The action buttons pattern is used and loved, but should not be actual buttons.  Let's re-think this design and make them more semantically correct and accessible.

**Comment by Blackbaud-LindseyRix** [comment]
Let's not do this in isolation. We follow a SKY UX design pattern of using action buttons for navigation. If we are coordinating our patterns, we shouldn't make this change alone.

**Comment by Blackbaud-BrandonJones** [comment]
Using the action buttons for navigation was not a SKY UX design pattern, it was a behavior we shoe-horned into our `stache-action-buttons` component.  This change would ideally not cause any of our users to have to do anything at all. It would be a semantic HTML change, behavior would remain the same.
