### ISSUE TITLE
Codeblock Style update

### ISSUE THREAD

**Issue by Blackbaud-BrandonJones** [blackbaud/stache2#507]
We should consider adding a "header" to the Stache code blocks, it could display the `languageType` and also contain the copy button.  See MS docs for the example 
https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-2.1&tabs=visual-studio

**Comment by Blackbaud-TimPepper** [comment]
This has been resolved by [#515](https://github.com/blackbaud/stache2/pull/515)

A header has been added that displays the code language and copy-to-clipboard button
