### ISSUE TITLE
Allow jsonData to contain folders for json data.

### ISSUE THREAD

**Issue by Blackbaud-BrandonJones** [blackbaud/stache2#508]
### Expected behavior
I should be able to have `stache/data/<some-folder>/data` and be able to access that jsonData.
### Actual behavior
only json files in the `data` folder directly are recognized.

**Comment by Blackbaud-TimPepper** [comment]
This has been resolved by [#39](https://github.com/blackbaud/skyux-builder-plugin-stache/pull/39)

Users may now created nested folders within the data folder and access the data accordingly.
