### ISSUE TITLE
Search: partial word and special character matching.

### ISSUE THREAD

**Issue by Blackbaud-BrandonJones** [blackbaud/stache2#511]
Shayde Nofziger:
Okay - I'm less concerned about partial-word matching, but the lack of `-` support makes this difficult for Powershell documentation support specifically.

But maybe I'll dig into those repos you posted and try to learn how it works

Though, if there were some way to get partial search working, that would be a lifesaver when it comes to our cmdlet documentation search, due to the way functions are named similarly. So I could type, for example, `Get-BBGuestCitrix` and it would show me all cmdlets that start with "Get-BBGuestCitrix". Though that would also require being able to search on symbols, as the hyphen splits the word.

Just some thoughts :slightly_smiling_face: Love how fast the search is though!

**Comment by Blackbaud-LindseyRix** [comment]
We made improvements to partial-word matching and overall search improvements. At this time we believe that this issue has been resolved, however if you are still experiencing a problem searching with partial words and special characters, please re-open add a comment.
