### ISSUE TITLE
Footer bug: Does not allow external `url` for a footer nav item

### ISSUE THREAD

**Issue by Blackbaud-LindseyRix** [blackbaud/stache2#520]
### Expected behavior

Provide `route` or `url` for a nav item

### Actual behavior

Route works fine. However, if you put in a url (like omnibar nav) for an external link, it doesn't build the link properly.

### Steps to reproduce

```
      "footer": {
        "nav": {
          "items": [
            {
              "title": "API Terms of Use",
              "route": "https://developer.sky.blackbaud.com/terms"
            }
          ]
        }
      }
```

Resulting link is: https://host.nxt.blackbaud.com/skyapi/https://developer.sky.blackbaud.com/terms 

Chrome can resolve this issue, but Footer should support a route or an external URL.

https://developer.blackbaud.com/skyapi/

**Comment by Blackbaud-BrandonJones** [comment]
Resolved with https://github.com/blackbaud/stache2/pull/522
