### ISSUE TITLE
Update the app-nav content in the Update Stache tutorial

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/stache2#524]
Step 5 of https://developer.blackbaud.com/stache/learn/update-stache provides guidance on implementing the app-nav component on Stache sites. It does not mention the omnibar even though we recommend using the omnibar for internal sites at https://developer.blackbaud.com/stache/learn/basics#application-navigation. I think we need to get Step 5 of the tutorial in sync with that section about application navigation. I think the guidance in the 2 locations should be consistent and either be populated by includes topics so that it is the same in both places or include x-refs if the 2 topics complement one another.

Stache is open source, so we need the app-nav guidance for external consumers, but the typical use case for Stache sites is internal, so we need to make sure the omnibar recommendation is clear. ... Also, I've never had to do the steps described in the tutorial, so I'm not sure if that's a change since the last time I implemented the app-nav component or if it's an optional item. I tried to test this, but I ran into issues creating a SPA to test this locally.

Also, I think the path that we specify in the tutorial is incorrect. I think it indicates an additional `app-nav` folder that is not actually in place when you create a Stache site. I think the app-nav files live one folder up. But again, I ran into issues creating a SPA locally, so I was not able to confirm this.

**Comment by Blackbaud-DeniseCisneros** [comment]
Fixed 
https://github.com/blackbaud/stache2-docs/pull/150
