### ISSUE TITLE
Deprecate Stache Grid in favor of Skyux Grid 

### ISSUE THREAD

**Issue by Blackbaud-BrandonJones** [blackbaud/stache2#526]
We should try and deprecate the Stache Grid in favor of the SKYUX grid as it supports more features than the current one we use.
https://github.com/blackbaud/skyux2/pull/1962#issuecomment-418721949

**Comment by Blackbaud-LindseyRix** [comment]
Can our Stache grid component remain, but in the back end utilize the SKY UX grid?

**Comment by Blackbaud-BrandonJones** [comment]
That's a possibility we will investigate first.  If not, it would require a breaking change to Stache  `3.0.0` release.  Which we would like to avoid until we have larger breaking changes that would need to happen.  If we do the breaking change release, none of our current consumers would automatically get that update, it would require a deliberate update to version 3, and the grid would need to be updated.

**Comment by Blackbaud-LindseyRix** [comment]
We have accomplished this in Stache version 3.0.0.
