### ISSUE TITLE
Add a "caption" input to images

### ISSUE THREAD

**Issue by Blackbaud-ThomasOrtiz** [blackbaud/stache2#527]
### Expected behavior
I should be able to add an optional `Description`  that displays centered underneath the image.

![image](https://user-images.githubusercontent.com/35976987/45178676-59ad7580-b1e4-11e8-9b71-a74fb8e2c1ec.png)

### Actual behavior
This is not currently so we can not give any additional context to images.

**Comment by Blackbaud-BrandonJones** [comment]
Resolved in release 2.11.4
https://github.com/blackbaud/stache2/pull/530
