### ISSUE TITLE
Edit button should open link in new tab/window

### ISSUE THREAD

**Issue by Blackbaud-ShaydeNofziger** [blackbaud/stache2#533]
### Expected behavior

When clicking the edit button component's anchor tag, I expect a new tab to open to the repo's file for editing.

### Actual behavior

The repo's file is opened in the same window I am viewing the documentation in, making it more cumbersome/difficult to view the rendered page and code simultaneously.

**Comment by Blackbaud-BrandonJones** [comment]
After mulling it over and discussing it, we are going to stick with the existing pattern we set for Stache sites.  Links open in the same window.  This allows users to decide for themselves which behavior they want the link to follow.  `right click + open in a new tab`,  `ctrl/cmd + click`, etc. for opening a new tab.
 
Thank you for the PR and filing an issue, we very much appreciate the efforts in contributing to Stache.
