### ISSUE TITLE
Investigate copy to clipboard simplification 

### ISSUE THREAD

**Issue by Blackbaud-BrandonJones** [blackbaud/stache2#549]
copy to clipboard may not be functioning in iOS, investigate and see if this simpler solution would work for us.

Ian Thomas [1:54 PM]
Hey Stache aficionados! :slightly_smiling_face: I've seen a few people across teams wanting to leverage the copy to clipboard functionality, my team included. We didn't feel like it was a good thing to depend on stache directly, so I ported the clipboard functionality (with a few minor modifications based on our workflow) over to our SPA.  I noticed last week that it wasn't working on iOS, so I started trying to find a better cross-browser solution.  I was able to find one that meets all my needs, and I wonder if it would be worthwhile to be evaluated for porting back into stache (or if you've already evaluated this path and rejected it for reasons worth sharing :stuck_out_tongue: ).

In the below PR, you can see a clipboard service within my SPA similar to the stache code.  The gist of the chage is that I found a browser polyfill library that I can depend on that removes all of the DOM manipulation code that I own. I have tested that this works cross-platform.
Stache probably needs a little more code than I do to copy from inputs, but this should still simplify it a lot.
https://blackbaud.visualstudio.com/Products/_git/skyux-spa-church-office/pullrequest/34290
https://github.com/lgarron/clipboard-polyfill

Ben Lambert [1:57 PM]
any reason not to make this a new skyux component (vs a stache component)?

**Comment by Blackbaud-LindseyRix** [comment]
This work has been completed.
